USE SADENADB
GO

SET NOCOUNT ON	
BEGIN TRY

	IF EXISTS( SELECT fi_oid FROM SDB.TAOficialias WITH( NOLOCK ))
	BEGIN
		DELETE FROM SDB.TAOficialias
	END
	--------------------------------------------------------------------------------------------------------------------------------      
	-- Responsable: Jorge Alberto de la Rosa  
	-- Fecha      : Diciembre 2018  
	-- Descripcion: Alta de registros de oficialias
	-- Aplicacion:  SADENADB  
	--------------------------------------------------------------------------------------------------------------------------------  
	IF NOT EXISTS( SELECT fi_oid FROM SDB.TAOficialias WITH( NOLOCK ))
	BEGIN	
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(1,33,5,7,1,'Pdte. Carranza S/N Centro Cp:27640','S/N ','Centro','27640','8696960116','Elvira María ','Borrego Cantú','','26.988161','-102.067376','')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(2,34,5,7,1,'Iturbide ','104','Centro','27640','8696960533','Ninfa Margarita ','Gonzalez Rodriguez','Notaria31gvj@hotmail.com','26.988785','-102.068005','')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(3,35,5,7,10,'Gabriel Villarreal','200','Centro','27640','55515114623','Herlinda','García Rico','','26.498152','-101.608564','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(4,38,5,9,1,' Zaragoza ','19','Madero','27900','8727732689','Gerónimo Alberto ','Gonzalez Martínez','mgl.3@hotmail.com','25.772338','-103.272002','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(5,39,5,9,1,'Constitución','36 BIS','Centro','27000/27900','8721100680','Francisco','Villa López','fcooficial03@hotmail.com','25.775578','-103.274187','')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(6,40,5,9,28,'Domicilio conocido ','S/N ','El Lequeitio','27915','8727736103','José Francisco','Lucio Ortiz','01lequeitio@hotmail.com','25.847744','-103.278826','No tiene equipamiento registrado')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(7,54,5,17,1,'Niños Héroes ','LOCAL10-2','Centro','27440','8717974159','Álvaro ','Ríos Pérez','alvaroriosperez.@hotmail.com','25.538903','-103.255537','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(8,55,5,17,1,'Pabellón Nte','8','Centro','27440','8717621035','Antonio ','Velázquez Quistian','perla_fernandez@hotmail.com','25.529999','-103.229704','')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(9,63,5,17,1,'CUAUTEMOC','510','CENTRO','27440','8717543024','Daniel','Sánchez Pérez','Danniiel_dsp@live.com.mx','25.531514','-103.233725','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(10,61,5,17,5,'Domicilio conocido','S/N ','Ej. Unión de Barreal','','NO TIENE','Porfirio ','Ramírez García','','25.426641','-103.160327','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(11,60,5,17,25,'Lázaro Cárdenas','113','Nueva','27441','8717627110','Fernando ','Reyes Gamez','','25.489997','-103.137338','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(12,56,5,17,12,'Domicilio conocido','S/N ','Ej. El Coyote','27454','8712681296','Ramón ','Sánchez Hernández','conchissd@hotmail.com ','25.693404','-103.286323','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(13,59,5,17,12,'Domicilio conocido','S/N ','Nueva','27454','8712412648','Ma. Concepción ','Pamanes Castañeda','PACM.481208@GMAIL.COM','25.696939','-103.284203','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(14,57,5,17,28,'Domicilio conocido','S/N ','Ej. El Manantial ','27470','8711253658','Martina','Espino Méndez','maitita200166@gmail.com','25.411334','-103.304987','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(15,58,5,17,122,'Carretera Vieja Torreón - San Pedro','S/N ','Ej. El Cambio','27455','8711502093','Francisco ','Ontiveros López','','25.64064','-103.334412','No tiene ficha')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(16,80,5,23,1,'Zaragoza','26','Centro','27500','8696950124','Carmen Elisa','Martínez Morales','carmene818@hotmail.com','27.313133','-102.396792','El equipo de cómputo es obsoleto')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(17,81,5,23,59,'Carretera A Ocampo Km. 1 ','','Centro','27500','5551512255','Miguel Ángel ','Jordán Hinojosa','','28.656779','-103.199234','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(18,82,5,23,453,'Fidel Velázquez ','4','Progreso','27630','8727752085','Juana ','López Martínez','juanylopez_12@hotmail.com','27.02309','-103.364333','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(19,83,5,24,1,'Reforma ','2-A','Centro','27980','8424221400','Jorge Francisco','Martínez Garza','primeraof@hotmail.com','25.437336','-102.184568','')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(20,84,5,24,1,'Muzquiz ','45','Centro','27980','8424221247','Ramiro ','Peña Rodriguez','oficialia02parras@hotmail.com','25.439742','-102.180532','')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(21,136,5,33,1,'Lerdo ','4','Centro','27800','8727727738','Aníbal','Morales Castillo','marco_nautylus@hotmail.com','25.755361','-102.983455','Computadoras, Escáneres e Impresoras no tienen dueño especificado')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(22,137,5,33,1,'Av. Morelos y Calle Viesca ','94','Centro','27800','8727725142','Javier','Padilla Lozano','japalo5401@gmail.com','25.759733','-102.980965','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(23,138,5,33,37,'Av. Miguel Hidalgo','239','Ejido Luchana','27970','8727734079','José Arturo','Morón Márquez','ARTUROMORAN_57@HOTMAIL.COM','25.791831','-103.197193','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(24,139,5,33,83,'Domicilio conocido ','S/N ','Ejido San Marcos ','27970','8721087248','Cristóbal ','Estrada Chairez','','25.66677','-103.009331','Computadoras, Escáneres e Impresoras no tienen dueño especificado')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(25,140,5,33,79,'Apartado Postal ','9','Ejido San Lorenzo','27942','8727789766','María Del Rosario ','Barrientos Guerrero','','25.721278','-103.15425','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(26,142,5,33,107,'Domicilio conocido ','S/N ','Ejido Tacubaya','27954','8721158753','María Caridad','María Caridad/Vázquez Avalos','Vázquez Avalos','25.684648','-103.069191','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(27,147,5,35,1,'Allende','840','Centro','27000','8717122245','Patricia Isabel ','Martínez Saucedo','OficialiaPrimera_Torreon@hotmail.com','25.541367','-103.458365','')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(28,150,5,35,1,'Allende','1118','Centro','27000','8717167085','Paulino ','Alfonso de La Cruz','LORE_YW@HOTMAIL.COM','25.541164','-103.461513','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(29,145,5,35,1,'Allende','239','Centro','27000','8717133244','Rafael ','García de Alba y Madero','galmara@yahoo.com','25.541401','-103.445992','')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(30,146,5,35,1,'Presidente Carranza Ote.','1764','Centro','27000','8717186767','Angelina Elvia','Colores Medina','angelinacolores@hotmail.com','25.53615','-103.429567','')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(31,153,5,35,1,'Blvd. Revolución','260 PTE.','Centro','27000','8717125234','María Del Pilar ','Hernández de Sotomayor','LORE_YW@HOTMAIL.COM','','','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(32,148,5,35,1,'División Del Norte ','161-A','Las Misiones','27268/27272','8712090399','Ma. Beatriz ','Granillo Vázquez','registrocivil11@hotmail.com','','','')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(33,161,5,35,1,'Madrid ','676','San Isidro','27100','8717189002','Luz Amelia','Boehringer Lugo','labcobo@hotmail.com','','','No especifica computadoras, escáneres e impresoras')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(34,163,5,35,1,'Mónaco','130','San Isidro','27100','8713478633','Oscar ','Calderón Flores','oscar.calder1980@yahoo.com','','','No especifica computadoras, escáneres e impresoras')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(35,158,5,35,1,'Av. Benito Juárez Ote.','146 INT.20','Centro','27000','8714102601','Melchor','Sánchez de La Fuente','LUIS_SIME@OUTLOOK.COM','','','No especifica computadoras, escáneres e impresoras')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(36,152,5,35,1,'División del Norte','295-3','Hacienda','27200','8712287636','Olga Rosa/ Alfredo Roberto','Soldo Hernández/Muñoz Arroyo','OLGA.ISOL@HOTMAIL.COM','','','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(37,162,5,35,1,'Encino','153','Jardín','27200','8717220744','Ángel ','García Castillo','xolsol@hotmail.com','','','')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(38,157,5,35,1,'Av. Ocampo ','653/659','Centro','27000','8712931813','Rogelio ','Wong Amaro','oficialia17@hotmail.com','','','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(39,156,5,35,1,'Niños Héroes Sur','273','Centro','27000','8717178399','Carolina Judith','Ortiz Aguilar','Oficialia19@hotmail.com','','','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(40,160,5,35,1,'Av. Xochimilco','267','Nueva California','27089','8717200423','Salvador Gerardo','Hernández Ávila','CRL_ANAHI@HOTMAIL.COM','','','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(41,164,5,35,1,'Hortencias ','8002','Jardines Universidad','','','Rodolfo ','Banda Meza','','','','No se encuentra en la base de datos')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(42,155,5,35,292,'Marfil ','53','La Joya','27400','8717322591','María Del Carmen ','Rodriguez Vázquez','MARI_BELROB@HOTMAIL.COM','','','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(43,151,5,35,180,'Domicilio conocido ','S/N ','','24412','8717116995','Apolonio','Pérez Castruita','OFICIALIA10LAPAZ@GMAIL.COM ','','','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(44,154,5,35,152,'Domicilio conocido Carretera Torreón San Pedro.','S/N ','La Concha','27420','8717506549','Virginia ','Pamanes Castañeda','VIKY50@HOTMAIL.COM.COM','','','No especifica computadoras escáneres e impresoras')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(45,165,5,36,1,'Independencia ','S/N ','Centro','27480','6711053587','Aristeo ','Lara Hernández','aristeo_lara52@hotmail.com','','','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(46,166,5,36,4,'Domicilio conocido ','S/N ','Ej. Boquila de las Perlas','27486','8711264727','Liliana Lilibeth ','Rodriguez Gómez','','','','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(47,167,5,36,14,'Domicilio conocido','S/N ','Ej. Gilita','27489','16717645112','Jorge Luis','Alba de la Cruz','','','','No especifica cantidad de mobiliario')
	INSERT INTO SDB.TAOficialias (fi_oid,fi_oficialia_id,fi_edo_id,fi_mpio_id,fi_loc_id,fc_calle,fc_numero,fc_colonia,fc_cp,fc_telefono,fc_nombres,fc_apellidos,fc_correo_e,fc_latitud,fc_longitud,fc_observaciones) VALUES(48,168,5,36,32,'Domicilio conocido Cordova ','S/N ','','27490','6711086748','Vicente','Adame Córdova','','','','No especifica cantidad de mobiliario')
	END
END TRY
BEGIN CATCH
	RAISERROR ('Error al insertar catálogos',18,1)      
	SET NOCOUNT OFF  
END CATCH