USE [master]
GO

/*
CREATE DATABASE [SADENADB] ON  PRIMARY 
( NAME = N'SADENADB', FILENAME = N'C:\Users\jalbo\DSI\WORKSPACES\SQLSERVER\SADENA\DB\DATA\SADENADB.mdf' , SIZE = 100MB , MAXSIZE = 1024GB, FILEGROWTH = 1024GB ),
( NAME = N'SADENADB_01', FILENAME = N'C:\Users\jalbo\DSI\WORKSPACES\SQLSERVER\SADENA\DB\DATA\SADENADB_01.ndf' , SIZE = 100MB , MAXSIZE = 1024GB, FILEGROWTH = 1024GB )
 LOG ON 
( NAME = N'SADENADB_log', FILENAME = N'C:\Users\jalbo\DSI\WORKSPACES\SQLSERVER\SADENA\DB\LOG\SADENADB_log.ldf' , SIZE = 100MB , MAXSIZE = 1024GB , FILEGROWTH = 1024GB )
GO
*/

CREATE DATABASE [SADENADB]

ALTER DATABASE [SADENADB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SADENADB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SADENADB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SADENADB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SADENADB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SADENADB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SADENADB] SET ARITHABORT OFF 
GO

ALTER DATABASE [SADENADB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SADENADB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SADENADB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SADENADB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SADENADB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SADENADB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SADENADB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SADENADB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SADENADB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SADENADB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SADENADB] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [SADENADB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SADENADB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SADENADB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SADENADB] SET PARAMETERIZATION FORCED 
GO

ALTER DATABASE [SADENADB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SADENADB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SADENADB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SADENADB] SET  MULTI_USER 
GO

ALTER DATABASE [SADENADB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SADENADB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SADENADB] SET  READ_WRITE 
GO


